name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  Pull-Request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn format-check

      - name: Unit & Integration tests
        run: yarn test

      - name: Deploy to Beta
        run: yarn run deploy:beta
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
